spring:
  jpa:
    database-platform:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: db_user
    password: y2KGz5mGyf

