version: '3.1'
services:
  app:
    build: .
    image: spring-boot-redis
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis

  redis:
    image: "redis:latest"
    hostname: redis
    ports:
      - "6379:6379"

