version: '3.1'
services:
  app:
    image: spring-boot-rabbitmq
    container_name: spring-boot-rabbitmq
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    build: rabbitmq/.
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USER=danilomr
      - RABBITMQ_PASSWORD=pass123
      - RABBITMQ_PID_FILE=/var/lib/rabbitmq/mnesia/rabbitmq
