version: '3.1'
services:
  app:
    image: spring-boot-postgres
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring_boot_postgres
      - SPRING_DATASOURCE_USERNAME=db_user
      - SPRING_DATASOURCE_PASSWORD=y2KGz5mGyf
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=y2KGz5mGyf
      - POSTGRES_USER=db_user
      - POSTGRES_DB=spring_boot_postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

